version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data source=db;Initial catalog=DummyDb;User id=sa;password=1K3nrj!ej3lR0ng;TrustServerCertificate=True"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1K3nrj!ej3lR0ng"
      ACCEPT_EULA: "Y"
